project:
  type: website
  output-dir: docs

website:
  title: "MIA TRENBEATH"
  navbar:
    right:
      - href: about.qmd
        text: ABOUT
      - href: projects.qmd
        text: PROJECTS
      - href: writing.qmd
        text: WRITING

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true
    page-layout: full



