project:
  type: website
  output-dir: docs
robots: noindex
website:
  title: MIA TRENBEATH
  navbar:
    right:
      - href: projects.qmd
        text: PROJECTS
      - href: writing.qmd
        text: WRITING
      - href: contact.qmd
        text: CONTACT
  page-footer:
    left: Â© Copyright 2025 Mia Trenbeath
    right: Built with [Github](https://github.com/mtrenbeath/miatrenbeath), [R](https://www.r-project.org/about.html), and [Quarto](https://quarto.org/)
    
format:
  html:
    include-font-awesome: true
    theme:
    - cosmo
    - styles.scss
    toc: true
    page-layout: full
    include-after-body: fa.html



